### ISSUE TITLE
Confirmation output presents box model instead of confirmation

### ISSUE THREAD

**Issue by cobaltgit** [OldDigibox/sky-box-lookup#5]
![image](https://user-images.githubusercontent.com/65132371/95202618-78263680-07d9-11eb-8b2c-6962b8ea1e87.png)

**Comment by 404invalid-user** [comment]
**done**
Check [This](https://github.com/OldDigibox/sky-box-lookup/pull/6)

**Comment by 404invalid-user** [comment]
I miss read it it should be fixed now in https://github.com/OldDigibox/sky-box-lookup/pull/7
